refactor!: dropped moment dependency, using Date() now
vinka-labs/clock pull request #12
Opened 2021-05-11 04:53 UTC by wuher

2021-05-11 08:50 UTC, veliaho requested changes
Moment, moment stringit pois tai rename niille

2021-05-11 08:50 UTC, veliaho commented on index.js
> +class Moment {
Pitäiskö tää olla osa Clock-luokkaa, tai Clock luokka perisi tämän? Heittää kaikki Moment, moment -stringit jonkkaan? Ettei hämäännyt sekoittamaan Moment kirjastoon

2021-05-12 08:16 UTC, wuher commented on index.js
> +class Moment {
Renamesin tämän `DateWrapper`ksi. Se on muutenkin paljon kuvaavampi nimi. Ehkä tuo riittää ettei tule sekaannuksia?

2021-05-12 08:18 UTC, veliaho approved these changes

2021-05-12 08:21 UTC, merged